name = "NonLinearBEM"
uuid = "ac4f66ef-b55e-4c44-9df1-dd60b59bb5cd"
authors = ["jay prakash <jayprakashdav20@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
